pool: Default

pr:
  - release

variables:
  dockerImageName: 'venkeyboda/spc'
  dockerImagetag:  '173' 

stages:
  - stage: CI
    jobs:
      - job: Deploy
        displayName: 'Deploy into cluster'
        steps:  
        - script: |
           sudo apt-get install wget apt-transport-https gnupg lsb-release -y
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update
            sudo apt-get install trivy -y  
          displayName: 'Install Trivy'  
        
        - script: trivy --version
          displayName: 'Check Trivy version'  

        - task: CmdLine@2
          displayName: 'Docker image Pull'
          inputs:
            script: |
              echo "Pulling image $(dockerImageName):$(dockerImagetag)"
              docker pull $(dockerImageName):$(dockerImagetag)


        - task: CmdLine@2
          displayName: 'scannig image '
          inputs:
            script: |
              trivy image $(dockerImageName):$(dockerImagetag) -o trivy-report.xml
    
        - task: PublishPipelineArtifact@1
          displayName: 'Publish Trivy Report'
          inputs:
            targetPath: 'trivy-report.xml'
            artifact: 'TrivyReport'

        - task: Bash@3
          displayName: 'terraform initialization'
          inputs:
            targetType: 'inline'
            script: |
              terraform init
              terraform apply -var-file="test.tfvars" -auto-approve
            workingDirectory: './infra'
        
        - task: Bash@3
          displayName: 'aks initialization'
          inputs:
            targetType: 'inline'
            script: |
              kubectl apply -f spc-deployement.yml
              kubectl get svc
