trigger:
  - develop

pool:
  vmImage: ubuntu-latest

pr: 
  - develop

variables:
  dockerImagerepo: 'venkeyboda/spc'
  dockerImagetag:  '$(Build.BuildId)' 

stages:
  - stage: CI
    jobs:
      - job: Build
        displayName: 'Building and Testing'
        steps:  
        - script: |
            sudo apt-get install rpm
            wget https://github.com/aquasecurity/trivy/releases/download/v0.9.1/trivy_0.9.1_Linux-64bit.deb
            sudo dpkg -i trivy_0.9.1_Linux-64bit.deb
          displayName: 'Install Trivy'  
        
        - script: trivy --version
          displayName: 'Check Trivy version'

        - script: |
            trivy image -o trivy-report.xml ***/spc:132
          displayName: 'Run Trivy scan'  

        - task: Maven@4
          displayName: 'build and publish the maven code'
          inputs:
            mavenPomFile: pom.xml
            goals: 'clean package'
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            publishJUnitResults: true
            javaHomeOption: 'JDKVersion'
            jdkVersionOption: '1.17'
            jdkArchitectureOption: 'x64'
        
        - task: CopyFiles@2
          inputs:
            contents: '**/*.jar'
            targetFolder: '$(Build.ArtifactStagingDirectory)'

        - task: PublishBuildArtifacts@1
          inputs:
            pathToPublish: '$(Build.ArtifactStagingDirectory)'
            artifactName: drop

        - task: Docker@2
          displayName: 'Build docker image'  
          inputs:
            command: 'build'
            Dockerfile: './Dockerfile'
            repository: $(dockerImagerepo)
            tags: |
              $(dockerImagetag)
        
        - task: CmdLine@2
          displayName: 'scannig image '
          inputs:
            script: |
              trivy image $(dockerImagerepo):$(dockerImagetag) -o trivy-report.xml

        - task: PublishPipelineArtifact@1
          displayName: 'Publish Trivy Report'
          inputs:
            targetPath: 'trivy-report.xml'
            artifact: 'TrivyReport'

        - task: Docker@2
          displayName: 'pushing the docker image'  
          inputs:
            command: 'push'
            containerRegistry: 'DOCKER_HUB'
            repository: $(dockerImagerepo)
            tags: |
              $(dockerImagetag)        

